apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jansankalp-ingress
  namespace: jansankalp-frontend
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
        - jansankalp.example.com
      secretName: jansankalp-tls
  rules:
    - host: jansankalp.example.com
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
          - path: /ai/?(.*)
            pathType: Prefix
            backend:
              service:
                name: ai-engine-service
                port:
                  number: 8000
