apiVersion: v1
kind: Namespace
metadata:
  name: jansankalp-frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: jansankalp-ai
---
apiVersion: v1
kind: Namespace
metadata:
  name: jansankalp-db
---
apiVersion: v1
kind: Namespace
metadata:
  name: jansankalp-monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: jansankalp-logging
